name: Python codeqa/test

on:
  pull_request:
    branches: "*"
  push:
    branches: "*"

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check code style with Flake8
      uses: TrueBrain/actions-flake8@v1.2
      with:
        path: src tests

  test:
    needs: [flake8]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [2.7, 3.5, 3.6, 3.8, pypy, pypy3]
        exclude:
        - os: ubuntu-latest
          python-version: 3.6
        - os: macos-latest
          python-version: 3.6
        - os: macos-latest
          python-version: pypy
        - os: macos-latest
          python-version: pypy3
        - os: windows-latest
          python-version: 2.7
        - os: windows-latest
          python-version: 3.5
        - os: windows-latest
          python-version: pypy
        - os: windows-latest
          python-version: pypy3
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade setuptools
      run: pip install "setuptools >= 40.9"
    - name: Install the project
      run: "pip install --no-binary=:all: ."
    - name: Install test dependencies
      run: pip install .[test]
    - name: Test with pytest
      run: python -b -m pytest -W always
